services:
  django:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: bash -c "cd project && python manage.py makemigrations
      && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      my_db:
        condition: service_healthy

  my_db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5433:5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - my_db

volumes:
  db_data:
