# Generated by Django 5.1.3 on 2024-11-30 14:45

import accounts.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Номер телефона в формате +79181234567', max_length=12, unique=True, validators=[accounts.services.phone_number_validator], verbose_name='Номер телефона')),
                ('pass_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='4-значный код для входа')),
                ('invite_code', models.CharField(blank=True, null=True, verbose_name='6-значный код-приглашение')),
                ('active_invite_code', models.CharField(blank=True, null=True, verbose_name='активированный 6-значный код-приглашение')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['phone_number'],
            },
        ),
    ]
