# Generated by Django 5.1.3 on 2024-11-30 17:06

import accounts.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона в формате +79181234567', max_length=12, validators=[accounts.services.phone_number_validator], verbose_name='Номер телефона'),
        ),
    ]
