# Generated by Django 5.1.3 on 2024-12-01 15:17

import accounts.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_pass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='активированный 6-значный код-приглашение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='6-значный код-приглашение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона в формате +79181234567', max_length=12, validators=[accounts.services.phone_number_validator], verbose_name='Номер телефона'),
        ),
    ]
